website_name: "From Chaos to Emergence"
website_tagline: "An attempt to organize, quantify and/or understand my thoughts and actions"

name: RM
email: rm.c0d3r@gmail.com

topics: [computers, maths, physics, general]

